# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

image: hashicorp/terraform:latest

stages:
  - validate
  - build
  - deploy

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate

build:
  stage: build
  script:
    - terraform plan -out=tfplan

deploy:
  stage: deploy
  script:
    - terraform apply tfplan
